### ISSUE TITLE
gRPC status/message not available with server-side streaming using Envoy

### ISSUE THREAD

**Issue by roboslone** [deeplay-io/nice-grpc#199]
I'm using Envoy with `grpc_web` filter [as recommended](https://github.com/deeplay-io/nice-grpc/tree/master/packages/nice-grpc-web#preparing-the-server). Downstream gRPC server is written in Go and uses `google.golang.org/grpc@1.48.0`, so no surprises there.

Protobuf is compiled using `ts-proto`.

When I'm trying to call server-streaming method, Envoy encodes both `grpc-status` and `grpc-message` to response body, *not headers*. This is visible in DevTools:
<img width="485" alt="Screenshot 2022-09-09 at 12 22 29" src="https://user-images.githubusercontent.com/1941275/189317753-5ee55243-7fcc-406c-bea9-e9d9200656ec.png">
<img width="845" alt="Screenshot 2022-09-09 at 12 22 15" src="https://user-images.githubusercontent.com/1941275/189317765-3544d8db-ebef-4c5e-a495-a4f6a4ad3e21.png">

Method definition looks like this:
```protobuf
    rpc List (merge.Task.BatchFilter) returns (stream merge.Task) {
        option (google.api.http).post = "/merge.TaskAPI/List";
    }
```

Client uses `grpc.CrossBrowserHttpTransport({ withCredentials: true })`.

On the client side, I get following error:
```
ClientError: /merge.TaskAPI/List UNKNOWN: Response closed without grpc-status (Headers only)
    at createServerStreamingMethod.ts:78:20
    at grpc-web-client.umd.js:1:11131
    at Array.forEach (<anonymous>)
    at e3.rawOnEnd (grpc-web-client.umd.js:1:11093)
    at e3.onTransportEnd (grpc-web-client.umd.js:1:10662)
    at grpc-web-client.umd.js:1:16760
```

If I understand this correctly, client-side code looks for status/message in headers.

This method (and a lot more others just like it) works fine with `@improbable-env/grpc-web` when using `grpc.invoke`. Is there some configuration option I'm missing?

**Comment by roboslone** [comment]
@aikoven can you please take a look at this? Thanks!

**Comment by roboslone** [comment]
Seems like [headers get in the way](https://github.com/improbable-eng/grpc-web/blob/84ab65f9526bd73430fb786dced98135186dd099/client/grpc-web/src/client.ts#L175). Not sure why this works without `nice-grpc-web` though.

**Comment by roboslone** [comment]
BTW, `onTrailer` is actually called on headers:
```ts
onHeader(headers) {
    for (const t of headers) {
        console.info('[header]', t[0], t.slice(1).join('; '))
    }
},
onTrailer(trailers) {
    for (const t of trailers) {
        console.info('[trailer]', t[0], t.slice(1).join('; '))
    }
},
```

Console:
```
[header] content-type application/grpc-web+proto
[header] x-b3-traceid 2d63f4a090dbe8eb
[header] x-request-id e903eded-efbb-9111-9e65-4f428c96933a
[trailer] content-type application/grpc-web+proto
[trailer] x-b3-traceid 2d63f4a090dbe8eb
[trailer] x-request-id e903eded-efbb-9111-9e65-4f428c96933a
```

**Comment by roboslone** [comment]
Not sure what I did, but it seems to be working now.

**Comment by aikoven** [comment]
Hey @roboslone, could you please share your envoy config? If it's working, we could include envoy setup in our tests and docs.

**Comment by roboslone** [comment]
It's somewhat specific, Envoy expect gRPC server on port 9090 and UI server on port 7070.
```yaml
admin:
  access_log_path: /tmp/access.admin.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
node:
  cluster: merge-envoy
  id: merge-envoy
static_resources:
  clusters:
  - connect_timeout: 0.25s
    load_assignment:
      cluster_name: envoy-admin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9901
    name: envoy-admin
    type: STATIC
  - connect_timeout: 0.25s
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: local-grpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9090
    name: local-grpc
    type: logical_dns
  - connect_timeout: 0.25s
    lb_policy: round_robin
    load_assignment:
      cluster_name: local-ui
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 7070
    name: local-ui
    type: logical_dns
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            virtual_hosts:
            - domains:
              - '*'
              name: https-redirect
              routes:
              - match:
                  prefix: /metrics
                route:
                  cluster: envoy-admin
                  prefix_rewrite: /stats/prometheus
                tracing:
                  random_sampling: {}
              - match:
                  prefix: /
                redirect:
                  https_redirect: true
          stat_prefix: http
    name: http
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8081
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
          codec_type: AUTO
          generate_request_id: true
          http_filters:
          - name: envoy.filters.http.grpc_web
          - name: envoy.filters.http.cors
          - name: envoy.filters.http.grpc_json_transcoder
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              convert_grpc_status: true
              print_options:
                add_whitespace: true
                always_print_enums_as_ints: false
                always_print_primitive_fields: true
                preserve_proto_field_names: false
              proto_descriptor: <PATH_TO_DESCRIPTOR>
              services:
              - merge.TaskAPI
          - name: envoy.filters.http.router
          route_config:
            name: local
            virtual_hosts:
            - cors:
                allow_credentials: true
                allow_headers: x-b3-traceid,grpc-status,grpc-message,grpc-status-details-bin,x-envoy-downstream-service-cluster,x-envoy-downstream-service-node,x-request-id,x-grpc-web,content-type,token
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_origin_string_match:
                - prefix: '*'
                expose_headers: x-b3-traceid,grpc-status,grpc-message,grpc-status-details-bin,x-envoy-downstream-service-cluster,x-envoy-downstream-service-node,x-request-id,x-grpc-web,content-type,token
              domains:
              - '*'
              name: main
              response_headers_to_add:
              - header:
                  key: x-b3-traceid
                  value: '%REQ(x-b3-traceid)%'
              - header:
                  key: x-envoy-downstream-service-cluster
                  value: '%REQ(x-envoy-downstream-service-cluster)%'
              - header:
                  key: x-envoy-downstream-service-node
                  value: '%REQ(x-envoy-downstream-service-node)%'
              - header:
                  key: x-request-id
                  value: '%REQ(x-request-id)%'
              routes:
              - match:
                  path: /
                redirect:
                  path_redirect: /ui
                tracing:
                  random_sampling: {}
              - match:
                  prefix: /ui/favicon.svg
                route:
                  cluster: local-ui
                  prefix_rewrite: /favicon.svg
                tracing:
                  random_sampling: {}
              - match:
                  prefix: /ui/robots.txt
                route:
                  cluster: local-ui
                  prefix_rewrite: /robots.txt
                tracing:
                  random_sampling: {}
              - match:
                  prefix: /ui/manifest.json
                route:
                  cluster: local-ui
                  prefix_rewrite: /manifest.json
                tracing:
                  random_sampling: {}
              - match:
                  prefix: /ui/logo192.png
                route:
                  cluster: local-ui
                  prefix_rewrite: /logo192.png
                tracing:
                  random_sampling: {}
              - match:
                  prefix: /ui/static
                route:
                  cluster: local-ui
                  prefix_rewrite: /static
                tracing:
                  random_sampling: {}
              - match:
                  prefix: /ui
                route:
                  cluster: local-ui
                tracing:
                  random_sampling: {}
              - match:
                  prefix: /metrics
                route:
                  cluster: envoy-admin
                  prefix_rewrite: /stats/prometheus
                tracing:
                  random_sampling: {}
              - match:
                  safe_regex:
                    google_re2: {}
                    regex: .*/Ping
                route:
                  cluster: local-grpc
                  timeout: 3s
                tracing:
                  random_sampling: {}
              - match:
                  prefix: /
                route:
                  cluster: local-grpc
                  retry_policy:
                    num_retries: 5
                    retry_back_off:
                      base_interval:
                        nanos: 50000000
                      max_interval: 3s
                  timeout: 900s
          stat_prefix: https
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols:
            - h2
            tls_certificates:
            - certificate_chain:
                filename: /ssl/crt
              private_key:
                filename: /ssl/key
    name: https
```
