### ISSUE TITLE
Adding auth header removes all other headers

### ISSUE THREAD

**Issue by jambudipa** [deeplay-io/nice-grpc#408]
I have an Angular app using `nice-grpc-web`, but when passing a bearer token to the authorisation header, it appears to remove all of the other headers, and so I am now getting CORS errors.

Before:
```
for await (const response of client.askQuestion({ query: question })) {
   // ...
}
// No complaints
```

After:
```
const metadata = new Metadata();
metadata.set('Authorization', `Bearer ${this.auth.getFirebaseIdToken()}`);

for await (const response of client.askQuestion({ query: question }, {
   metadata
})) {
   // ...
}
// Access to fetch at 'http://localhost:8081/ChatBot/AskQuestion' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.
```

How do I accomplish just adding this additional header?

**Comment by aikoven** [comment]
Hey,

What other headers are you talking about? How do you set them up?

As far as I can see from the error, it happens because the server did not respond with the correct `Access-Control-Allow-Headers` header. Which proxy server are you using? You can see an example of how to configure this for Envoy proxy [here](https://github.com/deeplay-io/nice-grpc/blob/e25d70ac3d241c17781797bfd075f2ade2f28268/packages/nice-grpc-web/test-server/envoy-tls.yaml#L43C27-L43C27).

**Comment by jambudipa** [comment]
Well I am using Envoy and I believe it is configured correctly. As I say, it is only when I add the metadata that the CORS errors arise. Without it, the call succeeds absolutely no problem.

Here are the two snapshots of the calls. The first without the metadata applied:

<img width="603" alt="Screenshot 2023-07-23 at 07 32 59" src="https://github.com/deeplay-io/nice-grpc/assets/116498499/b0230e88-5701-463d-8222-32312fff11b4">


And here, after the metadata is applied:

<img width="609" alt="Screenshot 2023-07-23 at 07 32 23" src="https://github.com/deeplay-io/nice-grpc/assets/116498499/7b33301b-959d-4d37-91b4-b0c4a1475e9c">



Not actually fully understanding that output if I'm honest.

**Comment by aikoven** [comment]
> As I say, it is only when I add the metadata that the CORS errors arise. Without it, the call succeeds absolutely no problem.

This is expected behavior. CORS prevents requests with headers from firing unless they are whitelisted.

Can you show your Envoy config? I'm pretty sure that allowed headers list lack the Authorization header.

**Comment by jambudipa** [comment]
Oh I see. Ok, when I’m back at my desk.Sent from my iPhoneOn 23 Jul 2023, at 08:02, Daniel Lytkin ***@***.***> wrote:﻿

As I say, it is only when I add the metadata that the CORS errors arise. Without it, the call succeeds absolutely no problem.

This is expected behavior. CORS prevents requests with headers from firing unless they are whitelisted.
Can you show your Envoy config? I'm pretty sure that allowed headers list lack the Authorization header.

**Comment by jambudipa** [comment]
```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8081 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: [ "*" ]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: api-gateway-proxy
                            timeout: 0s
                            auto_host_rewrite: true
                            max_stream_duration:
                              grpc_timeout_header_max: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.cors
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                  - name: envoy.filters.http.router
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
  clusters:
    - name: api-gateway-proxy
      type: logical_dns
      connect_timeout: 20s
      http2_protocol_options: { }
      lb_policy: round_robin
      dns_refresh_rate: 90s
      load_assignment:
        cluster_name: api-gateway-proxy
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 8080
      dns_lookup_family: V4_ONLY

```
